<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Report;
use Carbon\Carbon;

class ImportReportsSeeder extends Seeder
{
    public function run(): void
    {
        $reports = [
            [
                'id' => 2032,
                'companyName' => '',
                'firstname' => 'Marcel',
                'lastname' => 'Karger',
                'email' => 'm.karger@gmail.com',
                'plateCode1' => 'HN',
                'plateCode2' => 'BM',
                'plateCode3' => '898',
                'date' => '2021-02-04 11:05:37',
                'uploadStatus' => 0,
                'status' => 18,
                'sentStatus' => 1,
                'alreadyInSystem' => 0,
                'city' => 'Brackenheim',
                'zip' => '74336',
                'street' => 'Maulbronner Straße 8',
                'country' => 'Deutschland',
                'lat' => 0,
                'lng' => 0,
                'userId' => 14661,
                'addressId' => 1096,
                'created_at' => '2021-02-04 09:12:49',
                'updated_at' => '2022-05-23 16:17:25',
                'halterDatum' => '18.05.2022',
                'kbaFile' => 'https://p24-data.s3.amazonaws.com/kbaFiles/2032-Karger.pdf',
                'paymentStatus' => 0,
                'adminEmailSent' => 1,
            ],
            [
                'id' => 2033,
                'companyName' => 'Netattalk GmbH',
                'firstname' => 'Katja',
                'lastname' => 'Kriszio',
                'email' => 'kk@netattalk.de',
                'plateCode1' => 'LA',
                'plateCode2' => 'X',
                'plateCode3' => '184',
                'date' => '2021-02-09 07:57:01',
                'uploadStatus' => 0,
                'status' => 18,
                'sentStatus' => 1,
                'alreadyInSystem' => 0,
                'city' => 'Landshut',
                'zip' => '84034',
                'street' => 'Johannisstraße 24',
                'country' => 'Deutschland',
                'lat' => 0,
                'lng' => 0,
                'userId' => 11603,
                'addressId' => 809,
                'created_at' => '2021-02-09 09:18:51',
                'updated_at' => '2022-07-28 15:30:28',
                'mandantGeschlecht' => '2',
                'paymentStatus' => 0,
                'adminEmailSent' => 1,
            ],
            [
                'id' => 2034,
                'companyName' => '',
                'firstname' => 'Andreas',
                'lastname' => 'Krieger',
                'email' => 'kriegeraw@gmail.com',
                'plateCode1' => 'FS',
                'plateCode2' => 'FM',
                'plateCode3' => '720',
                'date' => '2021-02-13 14:53:23',
                'uploadStatus' => 0,
                'status' => 18,
                'sentStatus' => 1,
                'alreadyInSystem' => 0,
                'city' => 'Neufahrn bei Freising',
                'zip' => '85375',
                'street' => 'Grünecker Straße 2c',
                'country' => 'Deutschland',
                'lat' => 0,
                'lng' => 0,
                'userId' => 13292,
                'addressId' => 1160,
                'created_at' => '2021-02-13 14:02:37',
                'updated_at' => '2022-05-23 16:16:35',
                'paymentStatus' => 0,
                'adminEmailSent' => 1,
            ],
            [
                'id' => 2036,
                'companyName' => 'Sgw-ingenieurgesellschaft magdeburg mbh',
                'firstname' => 'Nicole',
                'lastname' => 'Steffens',
                'email' => 'Nicole.steffens@sgw-magdeburg.de',
                'plateCode1' => 'BK',
                'plateCode2' => 'AP',
                'plateCode3' => '464',
                'date' => '2021-02-18 18:00:34',
                'uploadStatus' => 0,
                'status' => 18,
                'sentStatus' => 1,
                'alreadyInSystem' => 0,
                'city' => 'Magdeburg',
                'zip' => '39112',
                'street' => 'Am Fuchsberg 6D',
                'country' => 'Deutschland',
                'lat' => 0,
                'lng' => 0,
                'userId' => 4544,
                'addressId' => 726,
                'created_at' => '2021-02-19 08:08:03',
                'updated_at' => '2022-05-23 16:17:03',
                'paymentStatus' => 0,
                'adminEmailSent' => 1,
            ],
            [
                'id' => 2037,
                'companyName' => '',
                'firstname' => 'Kerstin',
                'lastname' => 'Schnelling',
                'email' => 'kerstin.schnelling@gmx.de',
                'plateCode1' => 'MK',
                'plateCode2' => 'QB',
                'plateCode3' => '446',
                'date' => '2021-02-20 11:30:28',
                'uploadStatus' => 0,
                'status' => 18,
                'sentStatus' => 1,
                'alreadyInSystem' => 0,
                'city' => 'Hagen',
                'zip' => '58099',
                'street' => 'Grimmestraße 25',
                'country' => 'Deutschland',
                'lat' => 0,
                'lng' => 0,
                'userId' => 14089,
                'addressId' => 984,
                'created_at' => '2021-02-20 10:32:07',
                'updated_at' => '2022-05-23 16:15:39',
                'paymentStatus' => 0,
                'adminEmailSent' => 1,
            ],
            [
                'id' => 2067,
                'companyName' => '',
                'firstname' => 'Marcel',
                'lastname' => 'Karger',
                'email' => 'm.karger@gmail.com',
                'plateCode1' => 'HN',
                'plateCode2' => 'NW',
                'plateCode3' => '1005',
                'date' => '2021-03-15 09:50:33',
                'uploadStatus' => 0,
                'status' => 18,
                'sentStatus' => 1,
                'alreadyInSystem' => 0,
                'city' => 'Brackenheim',
                'zip' => '74336',
                'street' => 'Maulbronner Straße 8',
                'country' => 'Deutschland',
                'lat' => 0,
                'lng' => 0,
                'userId' => 14661,
                'addressId' => 1096,
                'created_at' => '2021-03-15 10:23:12',
                'updated_at' => '2022-05-23 16:16:04',
                'paymentStatus' => 0,
                'adminEmailSent' => 1,
            ],
            [
                'id' => 2275,
                'companyName' => 'Netattalk GmbH',
                'firstname' => 'Katja',
                'lastname' => 'Kriszio',
                'email' => 'kk@netattalk.de',
                'plateCode1' => 'DGF',
                'plateCode2' => 'L',
                'plateCode3' => '457',
                'date' => '2022-07-07 12:45:07',
                'uploadStatus' => 0,
                'status' => 14,
                'sentStatus' => 1,
                'alreadyInSystem' => 0,
                'city' => 'Landshut',
                'zip' => '84034',
                'street' => 'Johannisstr 24',
                'country' => 'Deutschland',
                'lat' => 0,
                'lng' => 0,
                'userId' => 11603,
                'addressId' => 809,
                'created_at' => '2022-07-11 06:16:56',
                'updated_at' => '2023-05-18 14:18:00',
                'halterDatum' => '19.07.2022',
                'halterName' => 'Siegfried Ibel',
                'halterPLZ' => '84180',
                'halterOrt' => 'Loiching',
                'halterStrasse' => 'Gewerbering 27',
                'paymentStatus' => 0,
                'adminEmailSent' => 1,
                'halterGeschlecht' => '1',
                'mandantGeschlecht' => '2',
                'notes' => '10.08.22:\r\n734/22\r\nGegner hat UE abgegeben, aber trotzdem noch Anwalt eingeschaltet. Was immer das auch soll. Bitte keine Mahnung verschicken.\r\n\r\n18.05.2023: Mandantin um Übersendung der Abtretungserklärung gebeten.',
                'ueFIle' => 'https://p24-data.s3.amazonaws.com/ueFiles/2275-Kriszio.pdf',
                'ueFileUploadedAt' => '2022-07-29 11:26:32',
            ],
            [
                'id' => 2276,
                'companyName' => '',
                'firstname' => 'Mike',
                'lastname' => 'Haubold',
                'email' => 'mike.haubold@gmail.com',
                'plateCode1' => 'GTH',
                'plateCode2' => 'CK',
                'plateCode3' => '129',
                'date' => '2022-07-11 10:21:00',
                'uploadStatus' => 0,
                'status' => 13,
                'sentStatus' => 1,
                'alreadyInSystem' => 0,
                'city' => 'Fröttstädt',
                'zip' => '99880',
                'street' => 'Am Bahnhof',
                'country' => 'Deutschland',
                'lat' => 0,
                'lng' => 0,
                'userId' => 17796,
                'addressId' => 1462,
                'created_at' => '2022-07-11 10:23:27',
                'updated_at' => '2022-11-22 07:56:34',
                'halterDatum' => '02.08.2022',
                'halterName' => 'Chris Konushevci',
                'halterPLZ' => '99880',
                'halterOrt' => 'Waltershausen',
                'halterStrasse' => 'Eisenacher Landstraße 21',
                'paymentStatus' => 0,
                'adminEmailSent' => 1,
                'halterGeschlecht' => '1',
                'notes' => '16.08.2022:\r\nFalschparker hat sich per E-Mail gemeldet und Fristverlängerung von 14 Tagen beantragt, weil er im Urlaub war. Ich werde die Frist um zwei Wochen, bis zum 30.08.2022, verlängern.\r\n\r\n30.08.2022:\r\nUE wurde abgegeben.\r\n\r\n29.08.2022:\r\nFalschparker hat per E-Mail mitgeteilt, dass die Unterlassungserklärung abgeschickt und die Rechtsanwaltskosten überwiesen wurden.',
                'ueFIle' => 'https://p24-data.s3.amazonaws.com/ueFiles/2276-Haubold.pdf',
                'ueFileUploadedAt' => '2022-08-30 14:34:48',
            ],
            // ... weitere Reports hier ...
        ];

        foreach ($reports as $reportData) {
            Report::create($reportData);
        }
    }
}
