services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: p24_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - p24_network

  nginx:
    image: nginx:alpine
    container_name: p24_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - p24_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: p24_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
    networks:
      - p24_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: p24_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8082:80"
    networks:
      - p24_network

networks:
  p24_network:
    driver: bridge
